---
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile

    image: nerfstudio-with-jupyter:latest
    restart: unless-stopped
    command: jupyter lab --port=8811 --ip=0.0.0.0 --NotebookApp.token="" --notebook-dir=/notebooks

    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8811:8811"
      - "7000-7100:7000-7100"
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/notebooks:/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
